/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcknowledgeAlertResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
}

impl AcknowledgeAlertResponse {
    pub fn new(status: String) -> AcknowledgeAlertResponse {
        AcknowledgeAlertResponse {
            schema: None,
            status,
        }
    }
}

