/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKey {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "last_used_at", deserialize_with = "Option::deserialize")]
    pub last_used_at: Option<String>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
}

impl ApiKey {
    pub fn new(
        created_at: String,
        identifier: String,
        last_used_at: Option<String>,
        name: String,
    ) -> ApiKey {
        ApiKey {
            created_at,
            identifier,
            last_used_at,
            name,
        }
    }
}
