/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppVersion {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "parameters")]
    pub parameters: Vec<models::Parameter>,
    /// The Towerfile that this version was created from.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "towerfile")]
    pub towerfile: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "version")]
    pub version: String,
}

impl AppVersion {
    pub fn new(
        created_at: String,
        parameters: Vec<models::Parameter>,
        towerfile: String,
        version: String,
    ) -> AppVersion {
        AppVersion {
            created_at,
            parameters,
            towerfile,
            version,
        }
    }
}
