/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.3.2
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppVersion {
    #[serde(rename = "parameters")]
    pub parameters: Vec<models::Parameter>,
    #[serde(rename = "version")]
    pub version: String,
}

impl AppVersion {
    pub fn new(parameters: Vec<models::Parameter>, version: String) -> AppVersion {
        AppVersion {
            parameters,
            version,
        }
    }
}

