/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.10
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppVersion {
    /// Server-computed SHA256 of the bundle contents for this version.
    #[serde(rename = "content_checksum", skip_serializing_if = "Option::is_none")]
    pub content_checksum: Option<String>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Client-supplied key (e.g. git SHA) that produced this version, or empty if none was supplied at deploy time.
    #[serde(rename = "idempotency_key", skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "parameters")]
    pub parameters: Vec<models::Parameter>,
    /// The Towerfile that this version was created from.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "towerfile")]
    pub towerfile: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "version")]
    pub version: String,
}

impl AppVersion {
    pub fn new(
        created_at: String,
        parameters: Vec<models::Parameter>,
        towerfile: String,
        version: String,
    ) -> AppVersion {
        AppVersion {
            content_checksum: None,
            created_at,
            idempotency_key: None,
            parameters,
            towerfile,
            version,
        }
    }
}
