/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppStatistics {
    #[serde(rename = "all_apps")]
    pub all_apps: i64,
    #[serde(rename = "disabled_apps")]
    pub disabled_apps: i64,
    #[serde(rename = "healthy_apps")]
    pub healthy_apps: i64,
    #[serde(rename = "running_apps")]
    pub running_apps: i64,
}

impl AppStatistics {
    pub fn new(all_apps: i64, disabled_apps: i64, healthy_apps: i64, running_apps: i64) -> AppStatistics {
        AppStatistics {
            all_apps,
            disabled_apps,
            healthy_apps,
            running_apps,
        }
    }
}

