/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppSummary {
    #[serde(rename = "app")]
    pub app: Box<models::App>,
    #[serde(rename = "runs")]
    pub runs: Vec<models::Run>,
}

impl AppSummary {
    pub fn new(app: models::App, runs: Vec<models::Run>) -> AppSummary {
        AppSummary {
            app: Box::new(app),
            runs,
        }
    }
}

