/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.7.6
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize, Deserializer};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppSummary {
    #[serde(rename = "app")]
    pub app: models::App,
    #[serde(rename = "runs")]
    pub runs: Vec<models::Run>,
}

impl AppSummary {
    pub fn new(app: models::App, runs: Vec<models::Run>) -> AppSummary {
        AppSummary {
            app,
            runs,
        }
    }
}

