/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.28
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationContext {
    /// The WorkOS access token for SSO authentication.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "work_os_access_token")]
    pub work_os_access_token: String,
}

impl AuthenticationContext {
    pub fn new(work_os_access_token: String) -> AuthenticationContext {
        AuthenticationContext {
            work_os_access_token,
        }
    }
}
