/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchedRunLogLines {
    #[serde(
        rename = "error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<Option<String>>,
    #[serde(rename = "log_lines", skip_serializing_if = "Option::is_none")]
    pub log_lines: Option<Vec<models::RunLogLine>>,
}

impl BatchedRunLogLines {
    pub fn new() -> BatchedRunLogLines {
        BatchedRunLogLines {
            error: None,
            log_lines: None,
        }
    }
}
