/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDescribeRunsLogsParams {
    /// Return only the first N log lines. Cannot be combined with tail.
    #[serde(
        rename = "head",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub head: Option<Option<i64>>,
    /// The name of the app to describe the run for.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    /// The number of the run to describe.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "seq")]
    pub seq: i64,
    /// Fetch logs from this timestamp onwards (inclusive).
    #[serde(
        rename = "start_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub start_at: Option<Option<String>>,
    /// Return only the last N log lines. Cannot be combined with head.
    #[serde(
        rename = "tail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tail: Option<Option<i64>>,
}

impl BatchDescribeRunsLogsParams {
    pub fn new(name: String, seq: i64) -> BatchDescribeRunsLogsParams {
        BatchDescribeRunsLogsParams {
            head: None,
            name,
            seq,
            start_at: None,
            tail: None,
        }
    }
}
