/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.12.6
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchRunAndLinks {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<models::RunAndLinks>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<models::BatchError>,
}

impl BatchRunAndLinks {
    pub fn new() -> BatchRunAndLinks {
        BatchRunAndLinks {
            data: None,
            error: None,
        }
    }
}
