/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDescribeRunsParams {
    /// The name of the app to describe the run for.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    /// The number of the run to describe.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "seq")]
    pub seq: i64,
}

impl BatchDescribeRunsParams {
    pub fn new(name: String, seq: i64) -> BatchDescribeRunsParams {
        BatchDescribeRunsParams { name, seq }
    }
}
