/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.12.6
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchError {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "message")]
    pub message: String,
}

impl BatchError {
    pub fn new(message: String) -> BatchError {
        BatchError { message }
    }
}
