/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.10.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelRunResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// Number of descendant runs that were also cancelled as part of this cascade.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "cancelled_child_runs")]
    pub cancelled_child_runs: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "run")]
    pub run: models::Run,
}

impl CancelRunResponse {
    pub fn new(cancelled_child_runs: i64, run: models::Run) -> CancelRunResponse {
        CancelRunResponse {
            schema: None,
            cancelled_child_runs,
            run,
        }
    }
}
