/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.12
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogCredentials {
    /// The Iceberg REST catalog endpoint.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "catalog_uri")]
    pub catalog_uri: String,
    /// When the OAuth token expires.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "expires_at")]
    pub expires_at: String,
    /// Access level the token is bound to.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "mode")]
    pub mode: String,
    /// Short-lived OAuth bearer token.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "oauth_token")]
    pub oauth_token: String,
    /// The Polaris catalog identifier (REST prefix).
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "warehouse")]
    pub warehouse: String,
}

impl CatalogCredentials {
    pub fn new(
        catalog_uri: String,
        expires_at: String,
        mode: String,
        oauth_token: String,
        warehouse: String,
    ) -> CatalogCredentials {
        CatalogCredentials {
            catalog_uri,
            expires_at,
            mode,
            oauth_token,
            warehouse,
        }
    }
}
