/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Catalog {
    #[serde(rename = "CreatedAt")]
    pub created_at: String,
    #[serde(rename = "environment")]
    pub environment: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "properties")]
    pub properties: Vec<models::CatalogProperty>,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl Catalog {
    pub fn new(created_at: String, environment: String, name: String, properties: Vec<models::CatalogProperty>, slug: String, r#type: String) -> Catalog {
        Catalog {
            created_at,
            environment,
            name,
            properties,
            slug,
            r#type,
        }
    }
}

