/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.7.6
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize, Deserializer};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogProperty {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "preview")]
    pub preview: String,
}

impl CatalogProperty {
    pub fn new(name: String, preview: String) -> CatalogProperty {
        CatalogProperty {
            name,
            preview,
        }
    }
}

