/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.29
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClaimDeviceLoginTicketParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The refresh token for the session to delegate to the device.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
    /// The user code to claim.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "user_code")]
    pub user_code: String,
}

impl ClaimDeviceLoginTicketParams {
    pub fn new(refresh_token: String, user_code: String) -> ClaimDeviceLoginTicketParams {
        ClaimDeviceLoginTicketParams {
            schema: None,
            refresh_token,
            user_code,
        }
    }
}
