/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePasswordResetResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// A boolean indicating the request was successfully processed.
    #[serde(rename = "ok")]
    pub ok: bool,
}

impl CreatePasswordResetResponse {
    pub fn new(ok: bool) -> CreatePasswordResetResponse {
        CreatePasswordResetResponse {
            schema: None,
            ok,
        }
    }
}

