/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.19
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAuthenticatorResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(rename = "authenticator")]
    pub authenticator: Box<models::VerifiedAuthenticator>,
}

impl CreateAuthenticatorResponse {
    pub fn new(authenticator: models::VerifiedAuthenticator) -> CreateAuthenticatorResponse {
        CreateAuthenticatorResponse {
            schema: None,
            authenticator: Box::new(authenticator),
        }
    }
}

