/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.28
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWebhookParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The name of the webhook.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    /// The webhook URL.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "url")]
    pub url: String,
}

impl CreateWebhookParams {
    pub fn new(name: String, url: String) -> CreateWebhookParams {
        CreateWebhookParams {
            schema: None,
            name,
            url,
        }
    }
}
