/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSandboxSecretsParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// Environment to create secrets in
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "environment")]
    pub environment: String,
    /// List of secret keys to create with Tower defaults
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "secret_keys")]
    pub secret_keys: Vec<String>,
}

impl CreateSandboxSecretsParams {
    pub fn new(environment: String, secret_keys: Vec<String>) -> CreateSandboxSecretsParams {
        CreateSandboxSecretsParams {
            schema: None,
            environment,
            secret_keys,
        }
    }
}
