/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.12
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateServiceAccountParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// Optional, customer-supplied JSON metadata.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
    /// Human-readable name for the service account. Must be unique within the account.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    /// The team role this service account acts as.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "role")]
    pub role: Role,
}

impl CreateServiceAccountParams {
    pub fn new(name: String, role: Role) -> CreateServiceAccountParams {
        CreateServiceAccountParams {
            schema: None,
            metadata: None,
            name,
            role,
        }
    }
}
/// The team role this service account acts as.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum Role {
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "developer")]
    Developer,
}

impl Default for Role {
    fn default() -> Role {
        Self::Admin
    }
}

impl<'de> Deserialize<'de> for Role {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "admin" => Ok(Self::Admin),
            "developer" => Ok(Self::Developer),
            _ => Err(serde::de::Error::unknown_variant(
                &s,
                &["admin", "developer"],
            )),
        }
    }
}
