/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: development
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDeviceLoginClaimParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub dollar_schema: Option<String>,
    /// The user code to claim.
    #[serde(rename = "user_code")]
    pub user_code: String,
}

impl CreateDeviceLoginClaimParams {
    pub fn new(user_code: String) -> CreateDeviceLoginClaimParams {
        CreateDeviceLoginClaimParams {
            dollar_schema: None,
            user_code,
        }
    }
}

