/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.26
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEnvironmentResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(rename = "environment")]
    pub environment: Box<models::Environment>,
}

impl CreateEnvironmentResponse {
    pub fn new(environment: models::Environment) -> CreateEnvironmentResponse {
        CreateEnvironmentResponse {
            schema: None,
            environment: Box::new(environment),
        }
    }
}

