/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.17
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAppParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// Indicates that web traffic should be routed to this app and that its runs should get a hostname assigned to it.
    #[serde(
        rename = "is_externally_accessible",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_externally_accessible: Option<bool>,
    /// The name of the app.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    /// The amount of time in seconds that runs of this app can stay in pending state before being marked as failed.
    #[serde(
        rename = "pending_timeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pending_timeout: Option<Option<i64>>,
    /// The retry policy for failed runs of this app. Defines different retry behavior for infrastructure (errored) vs application (crashed) failures.
    #[serde(rename = "retry_policy", skip_serializing_if = "Option::is_none")]
    pub retry_policy: Option<models::RunRetryPolicy>,
    /// The amount of time in seconds that runs of this app can stay in running state before being marked as failed.
    #[serde(
        rename = "running_timeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub running_timeout: Option<Option<i64>>,
    /// A description of the app.
    #[serde(rename = "short_description", skip_serializing_if = "Option::is_none")]
    pub short_description: Option<String>,
    /// The slug of the app. Legacy CLI will send it but we don't need it.
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// The subdomain this app is accessible under. Requires is_externally_accessible to be true.
    #[serde(
        rename = "subdomain",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub subdomain: Option<Option<String>>,
    /// The tags for this app.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<models::AppTag>>,
}

impl CreateAppParams {
    pub fn new(name: String) -> CreateAppParams {
        CreateAppParams {
            schema: None,
            is_externally_accessible: None,
            name,
            pending_timeout: None,
            retry_policy: None,
            running_timeout: None,
            short_description: None,
            slug: None,
            subdomain: None,
            tags: None,
        }
    }
}
