/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.10.14
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGuestParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The name of the externally accessible app this guest can access.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "app")]
    pub app: String,
    /// The number of seconds the guest session should last. Defaults to 72 hours.
    #[serde(rename = "expires_in", skip_serializing_if = "Option::is_none")]
    pub expires_in: Option<i64>,
    /// Optional display name for the guest.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Where to redirect the guest after they log in. Defaults to the app's subdomain.
    #[serde(rename = "redirect_url", skip_serializing_if = "Option::is_none")]
    pub redirect_url: Option<String>,
}

impl CreateGuestParams {
    pub fn new(app: String) -> CreateGuestParams {
        CreateGuestParams {
            schema: None,
            app,
            expires_in: None,
            name: None,
            redirect_url: None,
        }
    }
}
