/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSessionParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// One-time password verification code for two-factor authentication. If the user has two-factor authentication enabled, this code is required to log in.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "password")]
    pub password: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "username")]
    pub username: String,
}

impl CreateSessionParams {
    pub fn new(password: String, username: String) -> CreateSessionParams {
        CreateSessionParams {
            schema: None,
            code: None,
            password,
            username,
        }
    }
}
