/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAccountParamsFlagsStruct {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "is_test_account")]
    pub is_test_account: bool,
}

impl CreateAccountParamsFlagsStruct {
    pub fn new(is_test_account: bool) -> CreateAccountParamsFlagsStruct {
        CreateAccountParamsFlagsStruct { is_test_account }
    }
}
