/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteScheduleParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The IDs of the schedules to delete.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "ids")]
    pub ids: Vec<String>,
}

impl DeleteScheduleParams {
    pub fn new(ids: Vec<String>) -> DeleteScheduleParams {
        DeleteScheduleParams { schema: None, ids }
    }
}
