/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteApiKeyResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// Created API key
    #[serde(rename = "api_key")]
    pub api_key: Box<models::ApiKey>,
}

impl DeleteApiKeyResponse {
    pub fn new(api_key: models::ApiKey) -> DeleteApiKeyResponse {
        DeleteApiKeyResponse {
            schema: None,
            api_key: Box::new(api_key),
        }
    }
}

