/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteTeamResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The team that was just created
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "team")]
    pub team: models::Team,
}

impl DeleteTeamResponse {
    pub fn new(team: models::Team) -> DeleteTeamResponse {
        DeleteTeamResponse { schema: None, team }
    }
}
