/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.19
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteAuthenticatorParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The ID of the authenticator to delete
    #[serde(rename = "authenticator_id")]
    pub authenticator_id: String,
}

impl DeleteAuthenticatorParams {
    pub fn new(authenticator_id: String) -> DeleteAuthenticatorParams {
        DeleteAuthenticatorParams {
            schema: None,
            authenticator_id,
        }
    }
}

