/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.7.6
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize, Deserializer};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteScheduleResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(rename = "the schedules successfully deleted")]
    pub the_schedules_successfully_deleted: Vec<models::Schedule>,
}

impl DeleteScheduleResponse {
    pub fn new(the_schedules_successfully_deleted: Vec<models::Schedule>) -> DeleteScheduleResponse {
        DeleteScheduleResponse {
            schema: None,
            the_schedules_successfully_deleted,
        }
    }
}

