/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.12
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteServiceAccountApiKeyParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The API key identifier (with or without the 'sk-' prefix).
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "identifier")]
    pub identifier: String,
}

impl DeleteServiceAccountApiKeyParams {
    pub fn new(identifier: String) -> DeleteServiceAccountApiKeyParams {
        DeleteServiceAccountApiKeyParams {
            schema: None,
            identifier,
        }
    }
}
