/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: development
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DescribeDeviceLoginClaimResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The JWT token.
    #[serde(rename = "token")]
    pub token: String,
    /// The user information.
    #[serde(rename = "user")]
    pub user: Box<models::User>,
}

impl DescribeDeviceLoginClaimResponse {
    pub fn new(token: String, user: models::User) -> DescribeDeviceLoginClaimResponse {
        DescribeDeviceLoginClaimResponse {
            schema: None,
            token,
            user: Box::new(user),
        }
    }
}

