/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DescribeRunLinks {
    /// The URL of the next run, if any.
    #[serde(rename = "next", deserialize_with = "Option::deserialize")]
    pub next: Option<String>,
    /// The URL of the previous run, if any.
    #[serde(rename = "prev", deserialize_with = "Option::deserialize")]
    pub prev: Option<String>,
    /// The URL of this run.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "self")]
    pub param_self: String,
}

impl DescribeRunLinks {
    pub fn new(next: Option<String>, prev: Option<String>, param_self: String) -> DescribeRunLinks {
        DescribeRunLinks {
            next,
            prev,
            param_self,
        }
    }
}
