/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize, Deserializer};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DescribeEmailPreferencesBody {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(rename = "subscriptions")]
    pub subscriptions: models::EmailSubscriptions,
}

impl DescribeEmailPreferencesBody {
    pub fn new(subscriptions: models::EmailSubscriptions) -> DescribeEmailPreferencesBody {
        DescribeEmailPreferencesBody {
            schema: None,
            subscriptions,
        }
    }
}

