/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.10
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DescribeEnvironmentResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "environment")]
    pub environment: models::Environment,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "number_catalogs")]
    pub number_catalogs: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "number_schedules")]
    pub number_schedules: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "number_secrets")]
    pub number_secrets: i64,
}

impl DescribeEnvironmentResponse {
    pub fn new(
        environment: models::Environment,
        number_catalogs: i64,
        number_schedules: i64,
        number_secrets: i64,
    ) -> DescribeEnvironmentResponse {
        DescribeEnvironmentResponse {
            schema: None,
            environment,
            number_catalogs,
            number_schedules,
            number_secrets,
        }
    }
}
