/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EncryptedCatalogProperty {
    #[serde(rename = "encrypted_value")]
    pub encrypted_value: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "preview")]
    pub preview: String,
}

impl EncryptedCatalogProperty {
    pub fn new(encrypted_value: String, name: String, preview: String) -> EncryptedCatalogProperty {
        EncryptedCatalogProperty {
            encrypted_value,
            name,
            preview,
        }
    }
}

