/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.28
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventShouldertap {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "data")]
    pub data: models::ShoulderTap,
    /// The event name.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "event")]
    pub event: Event,
    /// The event ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The retry time in milliseconds.
    #[serde(rename = "retry", skip_serializing_if = "Option::is_none")]
    pub retry: Option<i32>,
}

impl EventShouldertap {
    pub fn new(data: models::ShoulderTap, event: Event) -> EventShouldertap {
        EventShouldertap {
            data,
            event,
            id: None,
            retry: None,
        }
    }
}
/// The event name.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum Event {
    #[serde(rename = "shouldertap")]
    Shouldertap,
}

impl Default for Event {
    fn default() -> Event {
        Self::Shouldertap
    }
}

impl<'de> Deserialize<'de> for Event {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "shouldertap" => Ok(Self::Shouldertap),
            _ => Err(serde::de::Error::unknown_variant(&s, &["shouldertap"])),
        }
    }
}
