/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportSecretsResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "pages")]
    pub pages: models::Pagination,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "secrets")]
    pub secrets: Vec<models::ExportedSecret>,
}

impl ExportSecretsResponse {
    pub fn new(
        pages: models::Pagination,
        secrets: Vec<models::ExportedSecret>,
    ) -> ExportSecretsResponse {
        ExportSecretsResponse {
            schema: None,
            pages,
            secrets,
        }
    }
}
