/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportedSecret {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "encrypted_value")]
    pub encrypted_value: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "environment")]
    pub environment: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
}

impl ExportedSecret {
    pub fn new(
        created_at: String,
        encrypted_value: String,
        environment: String,
        name: String,
    ) -> ExportedSecret {
        ExportedSecret {
            created_at,
            encrypted_value,
            environment,
            name,
        }
    }
}
