/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.7.6
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize, Deserializer};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportedCatalog {
    #[serde(rename = "CreatedAt")]
    pub created_at: String,
    #[serde(rename = "environment")]
    pub environment: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "properties")]
    pub properties: Vec<models::ExportedCatalogProperty>,
    /// This property is deprecated. Please use name instead.
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ExportedCatalog {
    pub fn new(created_at: String, environment: String, name: String, properties: Vec<models::ExportedCatalogProperty>, r#type: String) -> ExportedCatalog {
        ExportedCatalog {
            created_at,
            environment,
            name,
            properties,
            slug: None,
            r#type,
        }
    }
}

