/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportedCatalogProperty {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "encrypted_value")]
    pub encrypted_value: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "preview")]
    pub preview: String,
}

impl ExportedCatalogProperty {
    pub fn new(encrypted_value: String, name: String, preview: String) -> ExportedCatalogProperty {
        ExportedCatalogProperty {
            encrypted_value,
            name,
            preview,
        }
    }
}
