/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.5.1
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportUserSecretsParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(rename = "public_key")]
    pub public_key: String,
}

impl ExportUserSecretsParams {
    pub fn new(public_key: String) -> ExportUserSecretsParams {
        ExportUserSecretsParams {
            schema: None,
            public_key,
        }
    }
}

