/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.19
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeaturebaseIdentity {
    #[serde(rename = "company_hash")]
    pub company_hash: String,
    #[serde(rename = "user_hash")]
    pub user_hash: String,
}

impl FeaturebaseIdentity {
    pub fn new(company_hash: String, user_hash: String) -> FeaturebaseIdentity {
        FeaturebaseIdentity {
            company_hash,
            user_hash,
        }
    }
}

