/*
 * Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateAppStatisticsResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(rename = "statistics")]
    pub statistics: Box<models::AppStatistics>,
}

impl GenerateAppStatisticsResponse {
    pub fn new(statistics: models::AppStatistics) -> GenerateAppStatisticsResponse {
        GenerateAppStatisticsResponse {
            schema: None,
            statistics: Box::new(statistics),
        }
    }
}

