/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.4.3
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRunLogLine {
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl GetRunLogLine {
    pub fn new(channel: String, message: String, timestamp: String) -> GetRunLogLine {
        GetRunLogLine {
            channel,
            message,
            timestamp,
        }
    }
}

