/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.10.17
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Guest {
    /// The name of the app this guest can access.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "app")]
    pub app: String,
    /// When the guest was created.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The unique identifier for the guest.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "id")]
    pub id: String,
    /// Optional display name for the guest.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl Guest {
    pub fn new(app: String, created_at: String, id: String) -> Guest {
        Guest {
            app,
            created_at,
            id,
            name: None,
        }
    }
}
