/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSecretsResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(rename = "pages")]
    pub pages: Box<models::Pagination>,
    #[serde(rename = "secrets")]
    pub secrets: Vec<models::Secret>,
}

impl ListSecretsResponse {
    pub fn new(pages: models::Pagination, secrets: Vec<models::Secret>) -> ListSecretsResponse {
        ListSecretsResponse {
            schema: None,
            pages: Box::new(pages),
            secrets,
        }
    }
}

