/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: 0.10.23-preview
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListGuestsResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// List of guests.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "guests")]
    pub guests: Vec<models::Guest>,
}

impl ListGuestsResponse {
    pub fn new(guests: Vec<models::Guest>) -> ListGuestsResponse {
        ListGuestsResponse {
            schema: None,
            guests,
        }
    }
}
