/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.17
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCatalogFactsResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "facts")]
    pub facts: Vec<models::CatalogFact>,
}

impl ListCatalogFactsResponse {
    pub fn new(facts: Vec<models::CatalogFact>) -> ListCatalogFactsResponse {
        ListCatalogFactsResponse {
            schema: None,
            facts,
        }
    }
}
