/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.19
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAuthenticatorsResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(rename = "authenticators")]
    pub authenticators: Vec<models::VerifiedAuthenticator>,
}

impl ListAuthenticatorsResponse {
    pub fn new(authenticators: Vec<models::VerifiedAuthenticator>) -> ListAuthenticatorsResponse {
        ListAuthenticatorsResponse {
            schema: None,
            authenticators,
        }
    }
}

