/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAlertsResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// List of alerts
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "alerts")]
    pub alerts: Vec<models::Alert>,
    /// Pagination information
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "pages")]
    pub pages: models::Pagination,
}

impl ListAlertsResponse {
    pub fn new(alerts: Vec<models::Alert>, pages: models::Pagination) -> ListAlertsResponse {
        ListAlertsResponse {
            schema: None,
            alerts,
            pages,
        }
    }
}
