/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTeamMembersResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// All of the members of a team
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "team_members")]
    pub team_members: Vec<models::User>,
}

impl ListTeamMembersResponse {
    pub fn new(team_members: Vec<models::User>) -> ListTeamMembersResponse {
        ListTeamMembersResponse {
            schema: None,
            team_members,
        }
    }
}
