/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAlertsResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// List of alerts
    #[serde(rename = "alerts")]
    pub alerts: Vec<models::Alert>,
    /// Pagination information
    #[serde(rename = "pages")]
    pub pages: Box<models::Pagination>,
}

impl ListAlertsResponse {
    pub fn new(alerts: Vec<models::Alert>, pages: models::Pagination) -> ListAlertsResponse {
        ListAlertsResponse {
            schema: None,
            alerts,
            pages: Box::new(pages),
        }
    }
}

