/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApiKeysResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// List of API keys
    #[serde(rename = "api_keys")]
    pub api_keys: Vec<models::ApiKey>,
}

impl ListApiKeysResponse {
    pub fn new(api_keys: Vec<models::ApiKey>) -> ListApiKeysResponse {
        ListApiKeysResponse {
            schema: None,
            api_keys,
        }
    }
}

