/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.29
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Organization {
    /// The name of the organization
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    /// The user of the organization owner
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "owner")]
    pub owner: models::User,
}

impl Organization {
    pub fn new(name: String, owner: models::User) -> Organization {
        Organization { name, owner }
    }
}
