/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationStorageUsage {
    /// When the total was measured. Null when no measurement is available.
    #[serde(rename = "measured_at", deserialize_with = "Option::deserialize")]
    pub measured_at: Option<String>,
    /// Physical bytes across the organization's Tower-managed catalogs, including Iceberg metadata and not-yet-compacted snapshot history.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "total_bytes")]
    pub total_bytes: i64,
}

impl OrganizationStorageUsage {
    pub fn new(measured_at: Option<String>, total_bytes: i64) -> OrganizationStorageUsage {
        OrganizationStorageUsage {
            measured_at,
            total_bytes,
        }
    }
}
