/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.10.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationUsage {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// Number of active schedules in the organization.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "active_schedules")]
    pub active_schedules: models::UsageLimit,
    /// Number of applications in the organization.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "apps")]
    pub apps: models::UsageLimit,
    /// The name of the organization's base plan.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "base_plan_name")]
    pub base_plan_name: String,
    /// Number of compute minutes used in the current billing cycle.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "compute_minutes")]
    pub compute_minutes: models::UsageLimit,
    /// Number of users in the organization.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "members")]
    pub members: models::UsageLimit,
    /// The name of the organization.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "organization_name")]
    pub organization_name: String,
    /// Whether the organization has the ability to use self-hosted runners.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "self_hosted_runners")]
    pub self_hosted_runners: models::UsageLimit,
}

impl OrganizationUsage {
    pub fn new(
        active_schedules: models::UsageLimit,
        apps: models::UsageLimit,
        base_plan_name: String,
        compute_minutes: models::UsageLimit,
        members: models::UsageLimit,
        organization_name: String,
        self_hosted_runners: models::UsageLimit,
    ) -> OrganizationUsage {
        OrganizationUsage {
            schema: None,
            active_schedules,
            apps,
            base_plan_name,
            compute_minutes,
            members,
            organization_name,
            self_hosted_runners,
        }
    }
}
