/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pagination {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "num_pages")]
    pub num_pages: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "page")]
    pub page: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "page_size")]
    pub page_size: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "total")]
    pub total: i64,
}

impl Pagination {
    pub fn new(num_pages: i64, page: i64, page_size: i64, total: i64) -> Pagination {
        Pagination {
            num_pages,
            page,
            page_size,
            total,
        }
    }
}
