/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.29
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Parameter {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "default")]
    pub default: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "description")]
    pub description: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    #[serde(default)]
    #[serde(rename = "hidden")]
    pub hidden: bool,
}

impl Parameter {
    pub fn new(default: String, description: String, name: String) -> Parameter {
        Parameter {
            default,
            description,
            name,
            hidden: false,
        }
    }
}
