/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.10.17
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Parameter {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "default")]
    pub default: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "description")]
    pub description: String,
    /// Whether this parameter is hidden/secret. Defaults to false.
    #[serde(rename = "hidden", skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
}

impl Parameter {
    pub fn new(default: String, description: String, name: String) -> Parameter {
        Parameter {
            default,
            description,
            hidden: None,
            name,
        }
    }
}
