/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.28
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Plan {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "base_plan_name")]
    pub base_plan_name: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "end_at", skip_serializing_if = "Option::is_none")]
    pub end_at: Option<String>,
    #[serde(rename = "extras", skip_serializing_if = "Option::is_none")]
    pub extras: Option<Vec<models::Feature>>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "features")]
    pub features: Vec<models::Feature>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "id")]
    pub id: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "start_at")]
    pub start_at: String,
}

impl Plan {
    pub fn new(
        base_plan_name: String,
        created_at: String,
        features: Vec<models::Feature>,
        id: String,
        start_at: String,
    ) -> Plan {
        Plan {
            base_plan_name,
            created_at,
            end_at: None,
            extras: None,
            features,
            id,
            start_at,
        }
    }
}
