/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.10.17
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegenerateGuestLoginUrlResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The new login URL to share with the guest.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "login_url")]
    pub login_url: String,
    /// When the login URL expires.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "login_url_expires_at")]
    pub login_url_expires_at: String,
}

impl RegenerateGuestLoginUrlResponse {
    pub fn new(login_url: String, login_url_expires_at: String) -> RegenerateGuestLoginUrlResponse {
        RegenerateGuestLoginUrlResponse {
            schema: None,
            login_url,
            login_url_expires_at,
        }
    }
}
