/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResendTeamInvitationResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The team invitations that were resent
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "team_invitation")]
    pub team_invitation: models::TeamInvitation,
}

impl ResendTeamInvitationResponse {
    pub fn new(team_invitation: models::TeamInvitation) -> ResendTeamInvitationResponse {
        ResendTeamInvitationResponse {
            schema: None,
            team_invitation,
        }
    }
}
