/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunLinks {
    /// The number of the next run, if any.
    #[serde(rename = "next_number", deserialize_with = "Option::deserialize")]
    pub next_number: Option<i64>,
    /// The number of the previous run, if any.
    #[serde(rename = "prev_number", deserialize_with = "Option::deserialize")]
    pub prev_number: Option<i64>,
}

impl RunLinks {
    pub fn new(next_number: Option<i64>, prev_number: Option<i64>) -> RunLinks {
        RunLinks {
            next_number,
            prev_number,
        }
    }
}
