/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.28
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunRunInitiatorDetails {
    /// The name of the app that initiated this run, if type is 'tower_run'
    #[serde(rename = "run_app_name", skip_serializing_if = "Option::is_none")]
    pub run_app_name: Option<String>,
    /// The number of the run that initaited this run, if type is 'tower_run'
    #[serde(rename = "run_number", skip_serializing_if = "Option::is_none")]
    pub run_number: Option<i64>,
}

impl RunRunInitiatorDetails {
    pub fn new() -> RunRunInitiatorDetails {
        RunRunInitiatorDetails {
            run_app_name: None,
            run_number: None,
        }
    }
}
