/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunAndLinks {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "$links")]
    pub dollar_links: models::RunLinks,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "run")]
    pub run: models::Run,
}

impl RunAndLinks {
    pub fn new(dollar_links: models::RunLinks, run: models::Run) -> RunAndLinks {
        RunAndLinks { dollar_links, run }
    }
}
