/*
 * Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunStatistics {
    #[serde(rename = "failed_runs")]
    pub failed_runs: i64,
    #[serde(rename = "successful_runs")]
    pub successful_runs: i64,
    #[serde(rename = "total_runs")]
    pub total_runs: i64,
}

impl RunStatistics {
    pub fn new(failed_runs: i64, successful_runs: i64, total_runs: i64) -> RunStatistics {
        RunStatistics {
            failed_runs,
            successful_runs,
            total_runs,
        }
    }
}

