/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.10.15
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunAppParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The environment to run this app in.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "environment")]
    pub environment: String,
    /// Initiator information for this run
    #[serde(rename = "initiator", skip_serializing_if = "Option::is_none")]
    pub initiator: Option<models::RunAppInitiatorData>,
    /// The parameters to pass into this app.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "parameters")]
    pub parameters: std::collections::HashMap<String, String>,
    /// The ID of the run that invoked this run, if relevant. Should be null, if none.
    #[serde(
        rename = "parent_run_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_run_id: Option<Option<String>>,
    /// Override the retry policy for this specific run. If not provided, inherits from the app's retry policy.
    #[serde(rename = "retry_policy", skip_serializing_if = "Option::is_none")]
    pub retry_policy: Option<models::RunRetryPolicy>,
}

impl RunAppParams {
    pub fn new(
        environment: String,
        parameters: std::collections::HashMap<String, String>,
    ) -> RunAppParams {
        RunAppParams {
            schema: None,
            environment,
            initiator: None,
            parameters,
            parent_run_id: None,
            retry_policy: None,
        }
    }
}
