/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunGraphNode {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "id")]
    pub id: models::RunGraphRunId,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "parent_id")]
    pub parent_id: models::RunGraphRunId,
}

impl RunGraphNode {
    pub fn new(id: models::RunGraphRunId, parent_id: models::RunGraphRunId) -> RunGraphNode {
        RunGraphNode { id, parent_id }
    }
}
