/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.10.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunParameter {
    /// Whether this parameter is hidden/secret. Defaults to false.
    #[serde(rename = "hidden", skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    /// Whether this parameter's value was supplied as an override at run/schedule creation time (true) or comes from the app version's default (false).
    #[serde(
        rename = "is_override",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_override: Option<Option<bool>>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "value")]
    pub value: String,
}

impl RunParameter {
    pub fn new(name: String, value: String) -> RunParameter {
        RunParameter {
            hidden: None,
            is_override: None,
            name,
            value,
        }
    }
}
