/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunFailureAlert {
    /// App that the failed Run belongs to
    #[serde(rename = "app")]
    pub app: Box<models::App>,
    /// Run that failed
    #[serde(rename = "run")]
    pub run: Box<models::Run>,
}

impl RunFailureAlert {
    pub fn new(app: models::App, run: models::Run) -> RunFailureAlert {
        RunFailureAlert {
            app: Box::new(app),
            run: Box::new(run),
        }
    }
}

