/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunStatistics {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "cancelled_runs")]
    pub cancelled_runs: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "crashed_runs")]
    pub crashed_runs: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "errored_runs")]
    pub errored_runs: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "exited_runs")]
    pub exited_runs: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "running_runs")]
    pub running_runs: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "total_runs")]
    pub total_runs: i64,
}

impl RunStatistics {
    pub fn new(
        cancelled_runs: i64,
        crashed_runs: i64,
        errored_runs: i64,
        exited_runs: i64,
        running_runs: i64,
        total_runs: i64,
    ) -> RunStatistics {
        RunStatistics {
            cancelled_runs,
            crashed_runs,
            errored_runs,
            exited_runs,
            running_runs,
            total_runs,
        }
    }
}
