/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunStatistics {
    #[serde(rename = "cancelled_runs")]
    pub cancelled_runs: i64,
    #[serde(rename = "crashed_runs")]
    pub crashed_runs: i64,
    #[serde(rename = "errored_runs")]
    pub errored_runs: i64,
    #[serde(rename = "exited_runs")]
    pub exited_runs: i64,
    #[serde(rename = "running_runs")]
    pub running_runs: i64,
    #[serde(rename = "total_runs")]
    pub total_runs: i64,
}

impl RunStatistics {
    pub fn new(cancelled_runs: i64, crashed_runs: i64, errored_runs: i64, exited_runs: i64, running_runs: i64, total_runs: i64) -> RunStatistics {
        RunStatistics {
            cancelled_runs,
            crashed_runs,
            errored_runs,
            exited_runs,
            running_runs,
            total_runs,
        }
    }
}

