/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.7.6
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize, Deserializer};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunFailureAlert {
    /// App that the failed Run belongs to
    #[serde(rename = "app")]
    pub app: models::App,
    /// Run that failed
    #[serde(rename = "run")]
    pub run: models::Run,
}

impl RunFailureAlert {
    pub fn new(app: models::App, run: models::Run) -> RunFailureAlert {
        RunFailureAlert {
            app,
            run,
        }
    }
}

