/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.28
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunInitiator {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "details")]
    pub details: models::RunInitiatorDetails,
    /// The type of initiator for this run. Null if none or unknown.
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<String>,
}

impl RunInitiator {
    pub fn new(details: models::RunInitiatorDetails, r#type: Option<String>) -> RunInitiator {
        RunInitiator { details, r#type }
    }
}
