/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.10.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunRetryPolicy {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "max_retries")]
    pub max_retries: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "retry_delay_seconds")]
    pub retry_delay_seconds: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "use_exponential_backoff")]
    pub use_exponential_backoff: bool,
}

impl RunRetryPolicy {
    pub fn new(
        max_retries: i64,
        retry_delay_seconds: i64,
        use_exponential_backoff: bool,
    ) -> RunRetryPolicy {
        RunRetryPolicy {
            max_retries,
            retry_delay_seconds,
            use_exponential_backoff,
        }
    }
}
