/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: 0.10.23-preview
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunAttempt {
    /// When this attempt ended.
    #[serde(rename = "ended_at", deserialize_with = "Option::deserialize")]
    pub ended_at: Option<String>,
    /// Exit code for this attempt.
    #[serde(rename = "exit_code", deserialize_with = "Option::deserialize")]
    pub exit_code: Option<i64>,
    /// 1-based attempt number.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "seq")]
    pub seq: i64,
    /// When the run started executing your code.
    #[serde(rename = "started_at", deserialize_with = "Option::deserialize")]
    pub started_at: Option<String>,
    /// When the runner environment started to get setup.
    #[serde(rename = "starting_at", deserialize_with = "Option::deserialize")]
    pub starting_at: Option<String>,
    /// Terminal status of this attempt.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "status")]
    pub status: String,
}

impl RunAttempt {
    pub fn new(
        ended_at: Option<String>,
        exit_code: Option<i64>,
        seq: i64,
        started_at: Option<String>,
        starting_at: Option<String>,
        status: String,
    ) -> RunAttempt {
        RunAttempt {
            ended_at,
            exit_code,
            seq,
            started_at,
            starting_at,
            status,
        }
    }
}
