/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Runner {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "active_runs")]
    pub active_runs: Vec<models::Run>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "last_health_check_at",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_health_check_at: Option<String>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "max_concurrent_apps")]
    pub max_concurrent_apps: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "num_runs")]
    pub num_runs: i64,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "status")]
    pub status: String,
}

impl Runner {
    pub fn new(
        active_runs: Vec<models::Run>,
        created_at: String,
        id: String,
        max_concurrent_apps: i64,
        num_runs: i64,
        status: String,
    ) -> Runner {
        Runner {
            active_runs,
            created_at,
            id,
            last_health_check_at: None,
            max_concurrent_apps,
            num_runs,
            status,
        }
    }
}
