/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.7.6
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize, Deserializer};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Schedule {
    /// The name of the app that will be executed
    #[serde(rename = "app_name")]
    pub app_name: String,
    /// The specific app version to run, or null for the default version
    #[serde(rename = "app_version", skip_serializing_if = "Option::is_none")]
    pub app_version: Option<String>,
    /// The timestamp when the schedule was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The cron expression defining when the app should run
    #[serde(rename = "cron")]
    pub cron: String,
    /// The environment to run the app in
    #[serde(rename = "environment")]
    pub environment: String,
    /// The unique identifier for the schedule
    #[serde(rename = "id")]
    pub id: String,
    /// The parameters to pass when running the app
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<models::RunParameter>>,
    /// The timestamp when the schedule was last updated
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Schedule {
    pub fn new(app_name: String, created_at: String, cron: String, environment: String, id: String, updated_at: String) -> Schedule {
        Schedule {
            app_name,
            app_version: None,
            created_at,
            cron,
            environment,
            id,
            parameters: None,
            updated_at,
        }
    }
}

