/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Secret {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "environment")]
    pub environment: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "preview")]
    pub preview: String,
}

impl Secret {
    pub fn new(created_at: String, environment: String, name: String, preview: String) -> Secret {
        Secret {
            created_at,
            environment,
            name,
            preview,
        }
    }
}

