/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.7
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceAccountCreator {
    /// The creator's name: a user's full name (or email) or a service account's name.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    /// The kind of principal that created the service account. Always 'user'.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ServiceAccountCreator {
    pub fn new(name: String, r#type: Type) -> ServiceAccountCreator {
        ServiceAccountCreator { name, r#type }
    }
}
/// The kind of principal that created the service account. Always 'user'.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum Type {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "service_account")]
    ServiceAccount,
}

impl Default for Type {
    fn default() -> Type {
        Self::User
    }
}

impl<'de> Deserialize<'de> for Type {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "user" => Ok(Self::User),
            "service_account" => Ok(Self::ServiceAccount),
            _ => Err(serde::de::Error::unknown_variant(
                &s,
                &["user", "service_account"],
            )),
        }
    }
}
