/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.10
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceAccount {
    /// When the service account was created.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The user who created this service account.
    #[serde(rename = "creator", skip_serializing_if = "Option::is_none")]
    pub creator: Option<models::ServiceAccountCreator>,
    /// The unique identifier for the service account.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "metadata",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub metadata: Option<Option<serde_json::Value>>,
    /// The human-readable name of the service account.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    /// The team role this service account acts as.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "role")]
    pub role: Role,
    /// When the service account was last updated.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl ServiceAccount {
    pub fn new(
        created_at: String,
        id: String,
        name: String,
        role: Role,
        updated_at: String,
    ) -> ServiceAccount {
        ServiceAccount {
            created_at,
            creator: None,
            id,
            metadata: None,
            name,
            role,
            updated_at,
        }
    }
}
/// The team role this service account acts as.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum Role {
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "developer")]
    Developer,
}

impl Default for Role {
    fn default() -> Role {
        Self::Admin
    }
}

impl<'de> Deserialize<'de> for Role {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "admin" => Ok(Self::Admin),
            "developer" => Ok(Self::Developer),
            _ => Err(serde::de::Error::unknown_variant(
                &s,
                &["admin", "developer"],
            )),
        }
    }
}
