/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.7.6
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize, Deserializer};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Session {
    #[serde(rename = "featurebase_identity")]
    pub featurebase_identity: models::FeaturebaseIdentity,
    #[serde(rename = "teams")]
    pub teams: Vec<models::Team>,
    #[serde(rename = "token")]
    pub token: models::Token,
    #[serde(rename = "user")]
    pub user: models::User,
}

impl Session {
    pub fn new(featurebase_identity: models::FeaturebaseIdentity, teams: Vec<models::Team>, token: models::Token, user: models::User) -> Session {
        Session {
            featurebase_identity,
            teams,
            token,
            user,
        }
    }
}

