/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Session {
    #[serde(rename = "teams")]
    pub teams: Vec<models::Team>,
    #[serde(rename = "token")]
    pub token: Box<models::Token>,
    #[serde(rename = "user")]
    pub user: Box<models::User>,
}

impl Session {
    pub fn new(teams: Vec<models::Team>, token: models::Token, user: models::User) -> Session {
        Session {
            teams,
            token: Box::new(token),
            user: Box::new(user),
        }
    }
}

