/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.29
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShoulderTap {
    /// Account ID that owns the resource.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "account_id")]
    pub account_id: String,
    /// Event type in format resource.changed (e.g., apps.changed, runs.changed).
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "event_type")]
    pub event_type: String,
    /// Unique identifier of the resource.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "resource_id")]
    pub resource_id: String,
    /// Type of resource (apps, runs, schedules, secrets, environments, catalogs).
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "resource_type")]
    pub resource_type: String,
    /// Timestamp when the event occurred.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl ShoulderTap {
    pub fn new(
        account_id: String,
        event_type: String,
        resource_id: String,
        resource_type: String,
        timestamp: String,
    ) -> ShoulderTap {
        ShoulderTap {
            account_id,
            event_type,
            resource_id,
            resource_type,
            timestamp,
        }
    }
}
