/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatisticsSettings {
    /// The end time for the statistics period.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "end_at")]
    pub end_at: String,
    /// The environment to get statistics for.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "environment")]
    pub environment: String,
    /// The interval for the statistics period.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "interval")]
    pub interval: Interval,
    /// The start time for the statistics period.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "start_at")]
    pub start_at: String,
    /// The time zone for the statistics period.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "timezone")]
    pub timezone: String,
}

impl StatisticsSettings {
    pub fn new(
        end_at: String,
        environment: String,
        interval: Interval,
        start_at: String,
        timezone: String,
    ) -> StatisticsSettings {
        StatisticsSettings {
            end_at,
            environment,
            interval,
            start_at,
            timezone,
        }
    }
}
/// The interval for the statistics period.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum Interval {
    #[serde(rename = "daily")]
    Daily,
    #[serde(rename = "hourly")]
    Hourly,
}

impl Default for Interval {
    fn default() -> Interval {
        Self::Daily
    }
}

impl<'de> Deserialize<'de> for Interval {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "daily" => Ok(Self::Daily),
            "hourly" => Ok(Self::Hourly),
            _ => Err(serde::de::Error::unknown_variant(&s, &["daily", "hourly"])),
        }
    }
}
