/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.3
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatisticsSettings {
    #[serde(rename = "period")]
    pub period: String,
}

impl StatisticsSettings {
    pub fn new(period: String) -> StatisticsSettings {
        StatisticsSettings {
            period,
        }
    }
}

