/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.5.23
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StreamAlerts200ResponseInner {
    RunFailureAlert(models::RunFailureAlert),
    SseWarning(models::SseWarning),
}

impl Default for StreamAlerts200ResponseInner {
    fn default() -> Self {
        Self::RunFailureAlert(Default::default())
    }
}

