/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.27
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StreamAlerts200ResponseInner {
    EventError(Box<models::EventError>),
    EventRunFailureAlert(Box<models::EventRunFailureAlert>),
}

impl Default for StreamAlerts200ResponseInner {
    fn default() -> Self {
        Self::EventError(Default::default())
    }
}
/// The event name.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "run_failure_alert")]
    RunFailureAlert,
}

impl Default for Event {
    fn default() -> Event {
        Self::RunFailureAlert
    }
}

