/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.3.2
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StreamAppRunLogs200ResponseInner {
    EventMessage(Box<models::EventMessage>),
}

impl Default for StreamAppRunLogs200ResponseInner {
    fn default() -> Self {
        Self::EventMessage(Default::default())
    }
}
/// The event name.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "message")]
    Message,
}

impl Default for Event {
    fn default() -> Event {
        Self::Message
    }
}

