/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.5.23
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StreamRunLogs200ResponseInner {
    SseWarning(models::SseWarning),
    LogLine(models::LogLine),
}

impl Default for StreamRunLogs200ResponseInner {
    fn default() -> Self {
        Self::SseWarning(Default::default())
    }
}
/// The channel (either Program or Setup) this log line belongs to.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Channel {
    #[serde(rename = "program")]
    Program,
    #[serde(rename = "setup")]
    Setup,
}

impl Default for Channel {
    fn default() -> Channel {
        Self::Program
    }
}

