/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.28
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StreamShouldertaps200ResponseInner {
    EventShouldertap(models::EventShouldertap),
    EventWarning(models::EventWarning),
}

impl Default for StreamShouldertaps200ResponseInner {
    fn default() -> Self {
        Self::EventShouldertap(Default::default())
    }
}
/// The event name.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum Event {
    #[serde(rename = "warning")]
    Warning,
}

impl Default for Event {
    fn default() -> Event {
        Self::Warning
    }
}

impl<'de> Deserialize<'de> for Event {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "warning" => Ok(Self::Warning),
            _ => Err(serde::de::Error::unknown_variant(&s, &["warning"])),
        }
    }
}
