/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.26
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StreamRunLogs200ResponseInner {
    EventLog(Box<models::EventLog>),
    EventWarning(Box<models::EventWarning>),
}

impl Default for StreamRunLogs200ResponseInner {
    fn default() -> Self {
        Self::EventLog(Default::default())
    }
}
/// The event name.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "warning")]
    Warning,
}

impl Default for Event {
    fn default() -> Event {
        Self::Warning
    }
}

