/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StreamAlerts200ResponseInner {
    EventError(models::EventError),
    EventRunFailureAlert(models::EventRunFailureAlert),
}

impl Default for StreamAlerts200ResponseInner {
    fn default() -> Self {
        Self::EventError(Default::default())
    }
}
/// The event name.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum Event {
    #[serde(rename = "run_failure_alert")]
    RunFailureAlert,
}

impl Default for Event {
    fn default() -> Event {
        Self::RunFailureAlert
    }
}

impl<'de> Deserialize<'de> for Event {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "run_failure_alert" => Ok(Self::RunFailureAlert),
            _ => Err(serde::de::Error::unknown_variant(
                &s,
                &["run_failure_alert"],
            )),
        }
    }
}
