/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.17
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagFilter {
    /// The tag name to search.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "op")]
    pub op: Op,
    /// Required if operator is eq
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Required if operator is in or notIn
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

impl TagFilter {
    pub fn new(name: String, op: Op) -> TagFilter {
        TagFilter {
            name,
            op,
            value: None,
            values: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum Op {
    #[serde(rename = "eq")]
    Eq,
    #[serde(rename = "in")]
    In,
    #[serde(rename = "notIn")]
    NotIn,
}

impl Default for Op {
    fn default() -> Op {
        Self::Eq
    }
}

impl<'de> Deserialize<'de> for Op {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "eq" => Ok(Self::Eq),
            "in" => Ok(Self::In),
            "notIn" => Ok(Self::NotIn),
            _ => Err(serde::de::Error::unknown_variant(
                &s,
                &["eq", "in", "notIn"],
            )),
        }
    }
}
