/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.7.6
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize, Deserializer};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Team {
    #[serde(rename = "name")]
    pub name: String,
    /// This property is deprecated. Please use name instead.
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<models::Token>,
    /// The type of team, either 'personal' or 'team'.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl Team {
    pub fn new(name: String, r#type: String) -> Team {
        Team {
            name,
            slug: None,
            token: None,
            r#type,
        }
    }
}

