/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.10.17
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Team {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "execution_region")]
    pub execution_region: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    /// The name of the organization this team belongs to.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "organization")]
    pub organization: String,
    /// This property is deprecated. Use name instead.
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<models::Token>,
    /// The type of team, either 'personal' or 'team'.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "type")]
    pub r#type: String,
}

impl Team {
    pub fn new(
        execution_region: String,
        name: String,
        organization: String,
        r#type: String,
    ) -> Team {
        Team {
            execution_region,
            name,
            organization,
            slug: None,
            token: None,
            r#type,
        }
    }
}
