/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.28
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamInvitation {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "email")]
    pub email: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "invitation_sent_at")]
    pub invitation_sent_at: String,
    /// The name of the organization the user will move to if they accept this invitation
    #[serde(
        rename = "target_organization_name",
        skip_serializing_if = "Option::is_none"
    )]
    pub target_organization_name: Option<String>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "team")]
    pub team: models::Team,
    /// Indicates if accepting this invitation will move the user to a different organization
    #[serde(
        rename = "will_change_organization",
        skip_serializing_if = "Option::is_none"
    )]
    pub will_change_organization: Option<bool>,
}

impl TeamInvitation {
    pub fn new(email: String, invitation_sent_at: String, team: models::Team) -> TeamInvitation {
        TeamInvitation {
            email,
            invitation_sent_at,
            target_organization_name: None,
            team,
            will_change_organization: None,
        }
    }
}
