/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.29
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Token {
    /// The access token to use when authenticating API requests with Tower.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "jwt")]
    pub jwt: String,
    /// The refresh token to use when refreshing an expired access token. For security reasons, refresh tokens should only be transmitted over secure channels and never logged or stored in plaintext. It will only be returned upon initial authentication or when explicitly refreshing the access token.
    #[serde(rename = "refresh_token", skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
}

impl Token {
    pub fn new(access_token: String, jwt: String) -> Token {
        Token {
            access_token,
            jwt,
            refresh_token: None,
        }
    }
}
