/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnverifiedAuthenticator {
    /// The issuer of the unverified authenticator.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "issuer")]
    pub issuer: String,
    /// The key of the unverified authenticator.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "key")]
    pub key: String,
    /// The label that is used for this unverified authenticator.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "label")]
    pub label: String,
    /// The full URL of the authenticator.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "url")]
    pub url: String,
}

impl UnverifiedAuthenticator {
    pub fn new(issuer: String, key: String, label: String, url: String) -> UnverifiedAuthenticator {
        UnverifiedAuthenticator {
            issuer,
            key,
            label,
            url,
        }
    }
}
