/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(
        rename = "company",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub company: Option<Option<String>>,
    #[serde(
        rename = "country",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub country: Option<Option<String>>,
    #[serde(
        rename = "first_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub first_name: Option<Option<String>>,
    #[serde(
        rename = "is_alerts_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_alerts_enabled: Option<Option<bool>>,
    /// If true, the user will receive changelog updates via email.
    #[serde(
        rename = "is_subscribed_to_changelog",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_subscribed_to_changelog: Option<Option<bool>>,
    /// If true, the user will receive marketing emails from Tower.
    #[serde(
        rename = "is_subscribed_to_marketing_emails",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_subscribed_to_marketing_emails: Option<Option<bool>>,
    /// If true, the user will receive the Tower newsletter.
    #[serde(
        rename = "is_subscribed_to_newsletter",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_subscribed_to_newsletter: Option<Option<bool>>,
    #[serde(
        rename = "last_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_name: Option<Option<String>>,
    #[serde(
        rename = "password",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub password: Option<Option<String>>,
}

impl UpdateUserParams {
    pub fn new() -> UpdateUserParams {
        UpdateUserParams {
            schema: None,
            company: None,
            country: None,
            first_name: None,
            is_alerts_enabled: None,
            is_subscribed_to_changelog: None,
            is_subscribed_to_marketing_emails: None,
            is_subscribed_to_newsletter: None,
            last_name: None,
            password: None,
        }
    }
}
