/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSecretParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "encrypted_value")]
    pub encrypted_value: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "environment")]
    pub environment: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "preview")]
    pub preview: String,
}

impl UpdateSecretParams {
    pub fn new(
        encrypted_value: String,
        environment: String,
        preview: String,
    ) -> UpdateSecretParams {
        UpdateSecretParams {
            schema: None,
            encrypted_value,
            environment,
            preview,
        }
    }
}
