/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.29
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOrganizationResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The organization that was just updated
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "organization")]
    pub organization: models::Organization,
}

impl UpdateOrganizationResponse {
    pub fn new(organization: models::Organization) -> UpdateOrganizationResponse {
        UpdateOrganizationResponse {
            schema: None,
            organization,
        }
    }
}
