/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.29
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAppResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// Deprecated field. Use 'app' instead.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "App")]
    pub deprecated_app: models::App,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "app")]
    pub app: models::App,
}

impl UpdateAppResponse {
    pub fn new(deprecated_app: models::App, app: models::App) -> UpdateAppResponse {
        UpdateAppResponse {
            schema: None,
            deprecated_app,
            app,
        }
    }
}
