/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.10.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAppEnvironmentParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The version to deploy to this environment, e.g. 'v1', 'v2'.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "version")]
    pub version: String,
}

impl UpdateAppEnvironmentParams {
    pub fn new(version: String) -> UpdateAppEnvironmentParams {
        UpdateAppEnvironmentParams {
            schema: None,
            version,
        }
    }
}
