/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAccountParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// Whether the account is for self-hosted use only
    #[serde(
        rename = "is_self_hosted_only",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_self_hosted_only: Option<bool>,
    /// The new name for the account, if any
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl UpdateAccountParams {
    pub fn new() -> UpdateAccountParams {
        UpdateAccountParams {
            schema: None,
            is_self_hosted_only: None,
            name: None,
        }
    }
}
