/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.29
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTeamMemberParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The email address of the team member to update
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "email")]
    pub email: String,
    /// The role to update the team member to
    #[serde(
        rename = "role",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub role: Option<Option<Role>>,
}

impl UpdateTeamMemberParams {
    pub fn new(email: String) -> UpdateTeamMemberParams {
        UpdateTeamMemberParams {
            schema: None,
            email,
            role: None,
        }
    }
}
/// The role to update the team member to
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum Role {
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "developer")]
    Developer,
}

impl Default for Role {
    fn default() -> Role {
        Self::Admin
    }
}

impl<'de> Deserialize<'de> for Role {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "admin" => Ok(Self::Admin),
            "developer" => Ok(Self::Developer),
            _ => Err(serde::de::Error::unknown_variant(
                &s,
                &["admin", "developer"],
            )),
        }
    }
}
