/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.22
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAccountSlugParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The new slug for the account
    #[serde(rename = "new_slug")]
    pub new_slug: String,
}

impl UpdateAccountSlugParams {
    pub fn new(new_slug: String) -> UpdateAccountSlugParams {
        UpdateAccountSlugParams {
            schema: None,
            new_slug,
        }
    }
}

