/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.10.17
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAccountParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The execution region for runs (eu-central-1 or us-east-1)
    #[serde(rename = "execution_region", skip_serializing_if = "Option::is_none")]
    pub execution_region: Option<ExecutionRegion>,
    /// Whether the account is for self-hosted use only
    #[serde(
        rename = "is_self_hosted_only",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_self_hosted_only: Option<bool>,
    /// The new name for the account, if any
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl UpdateAccountParams {
    pub fn new() -> UpdateAccountParams {
        UpdateAccountParams {
            schema: None,
            execution_region: None,
            is_self_hosted_only: None,
            name: None,
        }
    }
}
/// The execution region for runs (eu-central-1 or us-east-1)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum ExecutionRegion {
    #[serde(rename = "eu-central-1")]
    EuCentral1,
    #[serde(rename = "us-east-1")]
    UsEast1,
}

impl Default for ExecutionRegion {
    fn default() -> ExecutionRegion {
        Self::EuCentral1
    }
}

impl<'de> Deserialize<'de> for ExecutionRegion {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "eu-central-1" => Ok(Self::EuCentral1),
            "us-east-1" => Ok(Self::UsEast1),
            _ => Err(serde::de::Error::unknown_variant(
                &s,
                &["eu-central-1", "us-east-1"],
            )),
        }
    }
}
