/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAccountNameResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(rename = "account")]
    pub account: Box<models::Account>,
}

impl UpdateAccountNameResponse {
    pub fn new(account: models::Account) -> UpdateAccountNameResponse {
        UpdateAccountNameResponse {
            schema: None,
            account: Box::new(account),
        }
    }
}

