/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.8.0
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAppParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// New description for the App
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "description")]
    pub description: String,
    /// Indicates that web traffic should be routed to this app and that its runs should get a hostname assigned to it.
    #[serde(
        rename = "is_externally_accessible",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_externally_accessible: Option<Option<bool>>,
    /// New status for the App
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "status")]
    pub status: String,
}

impl UpdateAppParams {
    pub fn new(description: String, status: String) -> UpdateAppParams {
        UpdateAppParams {
            schema: None,
            description,
            is_externally_accessible: None,
            status,
        }
    }
}
