/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.4
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAppParams {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// New description for the App
    #[serde(rename = "description")]
    pub description: String,
    /// New status for the App
    #[serde(rename = "status")]
    pub status: String,
}

impl UpdateAppParams {
    pub fn new(description: String, status: String) -> UpdateAppParams {
        UpdateAppParams {
            schema: None,
            description,
            status,
        }
    }
}

