/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.17
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCatalogFactBody {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// Optional structured payload (SQL, unit, enum values) as a JSON string.
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// How trustworthy the fact is.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "confidence")]
    pub confidence: Confidence,
    /// Descriptive path to what the fact is about, e.g. \"bronze.runs.deleted_at\". Empty for catalog-scoped facts.
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// What kind of object the fact is about.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "scope")]
    pub scope: Scope,
    /// Where the fact came from (agent id, user, ...).
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// The human-readable meaning of the fact.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "statement")]
    pub statement: String,
}

impl UpdateCatalogFactBody {
    pub fn new(confidence: Confidence, scope: Scope, statement: String) -> UpdateCatalogFactBody {
        UpdateCatalogFactBody {
            schema: None,
            body: None,
            confidence,
            object: None,
            scope,
            source: None,
            statement,
        }
    }
}
/// How trustworthy the fact is.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum Confidence {
    #[serde(rename = "confirmed")]
    Confirmed,
    #[serde(rename = "heuristic")]
    Heuristic,
    #[serde(rename = "inferred")]
    Inferred,
}

impl Default for Confidence {
    fn default() -> Confidence {
        Self::Confirmed
    }
}

impl<'de> Deserialize<'de> for Confidence {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "confirmed" => Ok(Self::Confirmed),
            "heuristic" => Ok(Self::Heuristic),
            "inferred" => Ok(Self::Inferred),
            _ => Err(serde::de::Error::unknown_variant(
                &s,
                &["confirmed", "heuristic", "inferred"],
            )),
        }
    }
}
/// What kind of object the fact is about.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum Scope {
    #[serde(rename = "catalog")]
    Catalog,
    #[serde(rename = "namespace")]
    Namespace,
    #[serde(rename = "table")]
    Table,
    #[serde(rename = "column")]
    Column,
    #[serde(rename = "metric")]
    Metric,
}

impl Default for Scope {
    fn default() -> Scope {
        Self::Catalog
    }
}

impl<'de> Deserialize<'de> for Scope {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "catalog" => Ok(Self::Catalog),
            "namespace" => Ok(Self::Namespace),
            "table" => Ok(Self::Table),
            "column" => Ok(Self::Column),
            "metric" => Ok(Self::Metric),
            _ => Err(serde::de::Error::unknown_variant(
                &s,
                &["catalog", "namespace", "table", "column", "metric"],
            )),
        }
    }
}
