/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.24
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VendCatalogCredentialsResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "credentials")]
    pub credentials: models::CatalogCredentials,
    /// Environment containing the catalog definition.
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "environment")]
    pub environment: String,
}

impl VendCatalogCredentialsResponse {
    pub fn new(
        credentials: models::CatalogCredentials,
        environment: String,
    ) -> VendCatalogCredentialsResponse {
        VendCatalogCredentialsResponse {
            schema: None,
            credentials,
            environment,
        }
    }
}
