/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.11.10
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VendCatalogCredentialsBody {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// Access level for the vended token. \"read\" (default) binds the token to the catalog's read-only principal; \"read-write\" requires the catalogs:update scope and binds it to the read-write principal.
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
}

impl VendCatalogCredentialsBody {
    pub fn new() -> VendCatalogCredentialsBody {
        VendCatalogCredentialsBody {
            schema: None,
            mode: None,
        }
    }
}
/// Access level for the vended token. \"read\" (default) binds the token to the catalog's read-only principal; \"read-write\" requires the catalogs:update scope and binds it to the read-write principal.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum Mode {
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "read-write")]
    ReadWrite,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Read
    }
}

impl<'de> Deserialize<'de> for Mode {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "read" => Ok(Self::Read),
            "read-write" => Ok(Self::ReadWrite),
            _ => Err(serde::de::Error::unknown_variant(
                &s,
                &["read", "read-write"],
            )),
        }
    }
}
