/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.6.19
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifiedAuthenticator {
    /// The ISO8601 timestamp indicating when this authenticator was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The ID of this authenticator
    #[serde(rename = "id")]
    pub id: String,
    /// The issuer of the unverified authenticator.
    #[serde(rename = "issuer")]
    pub issuer: String,
    /// The label that is used for this unverified authenticator.
    #[serde(rename = "label")]
    pub label: String,
}

impl VerifiedAuthenticator {
    pub fn new(created_at: String, id: String, issuer: String, label: String) -> VerifiedAuthenticator {
        VerifiedAuthenticator {
            created_at,
            id,
            issuer,
            label,
        }
    }
}

