/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.7.6
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize, Deserializer};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyEmailResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// The user that was verified
    #[serde(rename = "user")]
    pub user: models::User,
}

impl VerifyEmailResponse {
    pub fn new(user: models::User) -> VerifyEmailResponse {
        VerifyEmailResponse {
            schema: None,
            user,
        }
    }
}

