/*
 * Tower API
 *
 * REST API to interact with Tower Services.
 *
 * The version of the OpenAPI document: v0.9.28
 * Contact: hello@tower.dev
 * Generated by: https://openapi-generator.tech
 */
use crate::models;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{serde_as, DefaultOnNull};

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Webhook {
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "created_by_id")]
    pub created_by_id: String,
    #[serde(rename = "deleted_at", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<String>,
    #[serde(rename = "last_checked_at", deserialize_with = "Option::deserialize")]
    pub last_checked_at: Option<String>,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "name")]
    pub name: String,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "state")]
    pub state: State,
    #[serde_as(as = "DefaultOnNull")]
    #[serde(rename = "url")]
    pub url: String,
}

impl Webhook {
    pub fn new(
        account_id: String,
        created_at: String,
        created_by_id: String,
        last_checked_at: Option<String>,
        name: String,
        state: State,
        url: String,
    ) -> Webhook {
        Webhook {
            account_id,
            created_at,
            created_by_id,
            deleted_at: None,
            last_checked_at,
            name,
            state,
            url,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum State {
    #[serde(rename = "healthy")]
    Healthy,
    #[serde(rename = "unhealthy")]
    Unhealthy,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for State {
    fn default() -> State {
        Self::Healthy
    }
}

impl<'de> Deserialize<'de> for State {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "healthy" => Ok(Self::Healthy),
            "unhealthy" => Ok(Self::Unhealthy),
            "unknown" => Ok(Self::Unknown),
            _ => Err(serde::de::Error::unknown_variant(
                &s,
                &["healthy", "unhealthy", "unknown"],
            )),
        }
    }
}
