[project]
name = "tower-mock-api"
version = "0.1.0"
description = "A mock API server for Tower CLI testing."
dependencies = [
    "fastapi==0.111.0",
    "uvicorn==0.30.1",
]
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"